nginx: nginx -c `pwd`/nginx.conf
adapter: bundle exec env RACK_ENV=development NGX_OMNIAUTH_HOST=http://ngx-auth.127.0.0.1.nip.io:18080 rackup -p 18081 -o 127.0.0.1 ../config.ru
app: bundle exec ruby test_backend.rb -p 18082 -o 127.0.0.1
