name: ci
on: 
  pull_request:
    branches: [master]
  push:
    branches: [master, ci-test]

env:
  DOCKER_REPO: 'sorah/acmesmith'

jobs:
  test:
    name: rspec
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.7', '3.0', '3.1']
    container:
      image: public.ecr.aws/sorah/ruby:${{ matrix.ruby-version }}-dev
    steps:
      - name: Cache bundled gems
        uses: actions/cache@v3
        id: rspec-bundle
        with:
          path: ~/bundle
          key: ${{ runner.os }}-${{ matrix.ruby-version }}
      - uses: actions/checkout@v3
      - run: 'apt-get update && apt-get install -y --no-install-recommends nginx'
      - run: 'bundle install --path ~/bundle'
      - run: 'bundle exec rspec -fd'

        #docker-build:
        #  name: docker-build
        #  runs-on: ubuntu-latest
        #  steps:
        #    - uses: actions/checkout@master
        #    - run: 'echo $GITHUB_SHA > REVISION'

        #    - run: "docker pull ${DOCKER_REPO}:latest || :"
        #    - name: "docker tag ${DOCKER_REPO}:${TAG} ${DOCKER_REPO}:latest"
        #      run: |
        #        TAG=$(basename "${{ github.ref }}")
        #        docker pull ${DOCKER_REPO}:${TAG} || :
        #        docker tag ${DOCKER_REPO}:${TAG} ${DOCKER_REPO}:latest || :
        #      if: "${{ startsWith(github.ref, 'refs/tags/v') }}"

        #    - run: "docker pull ${DOCKER_REPO}:builder || :"

        #    - run: "docker build --pull --cache-from ${DOCKER_REPO}:builder --target builder -t ${DOCKER_REPO}:builder -f Dockerfile ."
        #    - run: "docker build --pull --cache-from ${DOCKER_REPO}:builder --cache-from ${DOCKER_REPO}:latest -t ${DOCKER_REPO}:${GITHUB_SHA} -f Dockerfile ."

        #    - run: "echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u sorah --password-stdin"
        #      if: "${{ github.event_name != 'pull_request' }}"

        #    - run: "docker push ${DOCKER_REPO}:builder"
        #      if: "${{ github.ref == 'refs/heads/master' }}"
        #    - run: "docker push ${DOCKER_REPO}:${GITHUB_SHA}"
        #      if: "${{ github.event_name != 'pull_request' }}"

        #docker-push:
        #  name: docker-push
        #  needs: [test, integration-pebble, docker-build]
        #  if: "${{ github.event_name == 'push' || github.event_name == 'create' }}"
        #  runs-on: ubuntu-latest
        #  steps:
        #    - run: "echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u sorah --password-stdin"
        #    - run: "docker pull ${DOCKER_REPO}:${GITHUB_SHA}"

        #    - run: |
        #        docker tag ${DOCKER_REPO}:${GITHUB_SHA} ${DOCKER_REPO}:latest
        #        docker push ${DOCKER_REPO}:latest
        #      if: "${{ github.ref == 'refs/heads/master' }}"
        #    - run: |
        #        TAG=$(basename "${{ github.ref }}")
        #        docker tag ${DOCKER_REPO}:${GITHUB_SHA} ${DOCKER_REPO}:${TAG}
        #        docker push ${DOCKER_REPO}:${TAG}
        #      if: "${{ startsWith(github.ref, 'refs/tags/v') }}"
